config/routes.rb
IdeaTest::Application.routes.draw do
  devise_for :users
  resources :ideas do
    resources :discussions
    resources :joins, only: :create do
      delete :destroy, on: :collection
    end
  end

  

  root 'ideas#index'

end

app/models/discussion.rb
class Discussion < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "post_missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_many :discussions

  belongs_to :user

  has_many :votes

  has_many :joins, dependent: :destroy
  has_many :users, through: :joins
  has_many :joiners, through: :joins, source: :user

  def update_vote_count
    self.votes_count = votes.up.count - votes.down.count
    save
  end

  def join_by user
    joiners << user 
  end

  def unjoin_by user
    joiners.delete(user) 
  end
end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :ideas
  has_many :discussions

  has_many :votes

  has_many :joins, dependent: :destroy
  has_many :ideas, through: :joins


  def name_display
    if first_name || last_name
      "#{first_name} #{last_name}".strip
    else
      email
    end
  end

  def vote_for idea
    Vote.where(idea: idea, user: self).first
  end

  def join_for idea
    joins.where(idea_id: idea.id).first
  end

  def has_joined? idea
    joined_ideas.include? idea
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea


  validates :user_id, uniqueness: {scope: :idea_id}
  
  scope :up,   -> { where(is_up: true) }
  scope :down, -> { where(is_up: false) }

  after_save :update_idea_vote_count
  after_destroy :update_idea_vote_count

  def is_down?
    !is_up?
  end

  private

  def update_idea_vote_count
    idea.update_vote_count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name]
  end
  
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :find_discussion, only: [:edit, :update, :show, :destroy]
  before_action :set_idea

  def new 
    @discussion = Discussion.new 
  end

  def create
    @discussion = current_user.discussions.new discussion_params
    @discussion.idea = @idea
    @discussion.user = current_user
    if @discussion.save
      DiscussionMailer.notify_owner(@discussion).deliver
      redirect_to @idea, notice: "Thanks for your contribution!"
    else
      render "ideas/show"
    end
    
  end

  def edit

  end

  def update
    @discussion.update_attributes(discussion_params)
    redirect_to @idea
  end

  def show

  end

  def destroy
    @discussion = Discussion.find(params[:id])
    if @discussion.user == current_user
      @discussion.destroy    
      redirect_to @idea, notice: "Discussion deleted successfully"
    else
      redirect_to @idea, notice: "Not cool man."      
    end
  end

  def discussion_params
    params.require(:discussion).permit([:title, :body, :image])
  end

  private

  def find_discussion
    @discussion = Discussion.find(params[:id])
  end

  def set_idea
    @idea = Idea.find params[:idea_id]
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:update]
  before_action :authenticate_user!, except: [:index, :show]

  def new 
    @idea = Idea.new 
  end

  def create
    @idea = current_user.ideas.new idea_params
    @idea.save
    redirect_to ideas_path
    #@idea.user = current_user
  end

  def index
    @ideas = Idea.all
  end

  def edit
    @idea = current_user.ideas.find(params[:id])
  end

  def update
    @idea.update_attributes(idea_params)
    redirect_to ideas_path
  end

  def show
    @idea = Idea.find(params[:id])
    @discussion = Discussion.new
  end

  def destroy
    @idea = Ideas.find(params[:id])
    @idea.destroy
    redirect_to ideas_path
  end

  def idea_params
    params.require(:idea).permit([:title, :body, :image])
  end

  def join
    @idea.save
    session[:joiners] ||= []
    session[:joiners] << @user.id
    redirect_to @idea
  end

  private

  def find_idea
    @idea = current_user.ideas.find(params[:id])
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_idea

  def create

    if @idea.join_by current_user
      redirect_to @idea, notice: "Thanks for liking the idea"
    else
      redirect_to @idea, notice: "Sorry there was trouble liking your idea."
    end
  end

  def destroy
    if @idea.unjoin_by current_user
      redirect_to @idea, notice: "The idea has been quit successfully."
    else
      redirect_to @idea, notice: "Sorry there was trouble liking your idea."
    end
  end

  private

  def find_idea
    @idea = current_user.ideas.find(params[:idea_id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_idea
  before_action :find_vote, only: [:update, :destroy]

  def create
    @vote      = @Idea.votes.new vote_params
    @vote.user = current_user
    if @vote.save
      redirect_to @idea, notice: "Vote recorded successfully!"
    else
      redirect_to @idea, notice: "Problem recording your vote"
    end
  end

  def update
    if @vote.update_attributes vote_params
      redirect_to @idea, notice: "Vote updated successfully!"
    else
      redirect_to @idea, notice: "Problem updating your vote"
    end
  end

  def destroy
    if @vote.destroy
      redirect_to @idea, notice: "Vote removed successfully!"
    else
      redirect_to @idea, notice: "Problem removing your vote"
    end
  end

  private

  def vote_params
    params.require(:vote).permit([:is_up])
  end

  def find_idea
    @idea = Idea.find(params[:idea_id])
  end

  def find_vote
    @vote = current_user.votes.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/discussions/edit.html.erb
<%= form_for [@idea, @discussion] do |f| %>
    <div class="form-group">
      <%= f.label :title, "Edit this discussion:" %>
      <br>
      <%= f.text_field :title, class: "form-control" %>
      
      <br>
      <%= f.text_area :body, class: "form-control"  %>
    </div>
    <%= f.submit class: "btn btn-default" %>
  <% end %>

app/views/discussions/new.html.erb
<h1>Enter a new idea</h1>
<%= render "form" %>

app/views/ideas/_form.html.erb
<%= form_for @idea do |f| %> 
  <% if @idea.errors.any? %>
    <ul class="alert_message">
      <% @idea.errors.messages.values.each do |message| %>      
      <li><%= message.join "," %></li>
      <% end %>
    </ul>

  <% end %>
  <div class="form-group">
  <%= f.label :title, "Best Idea Yet:" %>
  <%= f.text_field :title, class: "form-control" %>
  </div>
  <br>  

  <div class="form-group">
    <%= f.label :body, "Project Description" %>
    <%= f.text_area :body, class: "form-control" %>
    <br>
  </div>    

  
  <%= f.file_field :image, class: "btn btn-default" %>
  

  <%= f.submit "Submit", class: "btn btn-default" %>
  <%= link_to "Back", ideas_path, class: "btn btn-default" %>

<% end %>

app/views/ideas/edit.html.erb
<h1>Edit your idea</h1>
<%= render "form" %>

app/views/ideas/index.html.erb
<h1>Idea Factory</h1>
<%= link_to "New Idea", new_idea_path, class: "btn btn-default" %>
<hr>
<% @ideas.each do |idea| %>
  <%= image_tag idea.image.url(:medium) %>
  <p><%= link_to "#{idea.title}", idea %></p>
  <p><%= idea.body %></p>
  <%= link_to "Delete Idea", idea, method: :delete, data: {confirm: "Are you sure you want to delete this idea?"}, class: "btn btn-default" %>
  <%= link_to "Edit", edit_idea_path(idea)%>
  <% if user_signed_in? %>
    <% if idea.join_by current_user %>
      <%= link_to "Quit", idea_joins_path(idea), method: :delete %>
    <% else %>
      <%= link_to "Join", idea_joins_path(idea), method: :post %>
    <% end %>
  <% end %>
  <%#= render "/votes/vote_buttons", idea: @idea %>
  <hr>
<% end %>

app/views/ideas/new.html.erb
<h1>Enter a new idea</h1>
<%= render "form" %>

app/views/ideas/show.html.erb
<div class="idea-box">
  <h1><strong>Idea: </strong><%= @idea.title %></h1>
  <%= image_tag @idea.image(:medium) %>
  <p><strong>Description: </strong><%= @idea.body %></p>

<% if @discussion.errors.any? %>
    <ul>
      <% @discussion.errors.messages.values.each do |msg| %>
      <li><%= msg.join " " %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for [@idea, @discussion] do |f| %>
    <div class="form-group">
      <%= f.label :title, "Enter New discussion:" %>
      <br>
      <%= f.text_field :title, class: "form-control" %>
      
      <br>
      <%= f.text_area :body, class: "form-control"  %>
    </div>
    <%= f.submit class: "btn btn-default" %>
<% end %>

<hr>
  <h2>Discussions:</h2>
  <% @idea.discussions.each do |discussion| %>
    <h3><%= link_to "#{discussion.title}", idea_discussion_path(@idea, discussion) %></h3>
    <%= discussion.body %>

    <br>
    <br>

      <%= link_to "Delete Discussion", [@idea, discussion], method: :delete, data: {confirm: "Are you sure you want to delete this answer?"}, class: "btn btn-default" %>    
      <%= link_to "Edit Discussion", edit_idea_discussion_path(@idea, discussion), class: "btn btn-default" %>


    

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IdeaTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <ul class="nav navbar-nav  navbar-left">
      <li><h1><%= link_to "Idea Factory", root_path %></h1></li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <!-- <li>
        <%= form_tag("/search", method: "get") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
        <% end %>
      </li> -->
      <li class="pull-right">
        <div>
          <p>
            <% if user_signed_in? %>
              Hello <%= link_to current_user.name_display, edit_user_registration_path %>, 
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path %>
              |
              <%= link_to "Sign In", new_user_session_path %>
            <% end %>
          </p>
        </div>
      </li>

    </ul>
  </nav>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
  <% elsif flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/votes/_vote_buttons.html.erb
<% if user_signed_in? %>
  <% vote = current_user.vote_for(idea) || Vote.new %>
  <% if vote.persisted? && vote.is_up? %>
    <%= link_to "UnVote", [idea, vote], class: "btn btn-danger", method: :delete %>
    <br>
  <% else %>
    <%= render "/votes/vote_form", vote: vote, idea: idea, is_up: true, label: "Up Vote" %>
  <% end %>
  Vote Count: <%= idea.votes_count %>
  <br>
  <% if vote.persisted? && vote.is_down? %>
    <%= link_to "UnVote", [idea, vote], class: "btn btn-danger", method: :delete %>
  <% else %>
    <%= render "/votes/vote_form", vote: vote, idea: idea, is_up: false, label: "Down Vote" %>
  <% end %>

<% end %>
<br>
<br>

app/views/votes/_vote_form.html.erb
<%= form_for [idea, vote] do |f| %>
  <%= f.hidden_field :is_up, as: :hidden, value: is_up %>
  <%= f.submit label, class: "btn btn-danger" %>
<% end %>